# This rule is not used by the project custom-resources-selfadapter-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to customresourcesselfdapter.net.custom-resources-selfadapter.net resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: custom-resources-selfadapter-operator
    app.kubernetes.io/managed-by: kustomize
  name: customresourcesselfadapter-viewer-role
rules:
- apiGroups:
  - customresourcesselfdapter.net.custom-resources-selfadapter.net
  resources:
  - customresourcesselfadapters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - customresourcesselfdapter.net.custom-resources-selfadapter.net
  resources:
  - customresourcesselfadapters/status
  verbs:
  - get
