# This rule is not used by the project custom-resources-selfadapter-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over customresourcesselfdapter.net.custom-resources-selfadapter.net.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: custom-resources-selfadapter-operator
    app.kubernetes.io/managed-by: kustomize
  name: customresourcesselfadapter-admin-role
rules:
- apiGroups:
  - customresourcesselfdapter.net.custom-resources-selfadapter.net
  resources:
  - customresourcesselfadapters
  verbs:
  - '*'
- apiGroups:
  - customresourcesselfdapter.net.custom-resources-selfadapter.net
  resources:
  - customresourcesselfadapters/status
  verbs:
  - get
