# This rule is not used by the project custom-resources-selfadapter-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the customresourcesselfdapter.net.custom-resources-selfadapter.net.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: custom-resources-selfadapter-operator
    app.kubernetes.io/managed-by: kustomize
  name: customresourcesselfadapter-editor-role
rules:
- apiGroups:
  - customresourcesselfdapter.net.custom-resources-selfadapter.net
  resources:
  - customresourcesselfadapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customresourcesselfdapter.net.custom-resources-selfadapter.net
  resources:
  - customresourcesselfadapters/status
  verbs:
  - get
